### ISSUE TITLE
[Bug] Parsing error loading recipe

### ISSUE THREAD

**Issue by Sheridan** [SuperMartijn642/Wormhole#56]
**Version Info**
- Minecraft 1.20.4
- Wormhole 1.1.15-fabric-mc1.20.2

**Description of the Bug**
```
апр 22 14:47:30 gate minecraft[689295]: [14:47:30] [main/ERROR]: Parsing error loading recipe wormhole:advanced_energy_cell
апр 22 14:47:30 gate minecraft[689295]: com.google.gson.JsonParseException: Not a JSON object: null
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_156.method_47526(class_156.java:1005) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_1863.method_17720(class_1863.java:131) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
апр 22 14:47:30 gate minecraft[689295]:         at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_156.method_43498(class_156.java:944) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_156.method_43499(class_156.java:932) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.server.Main.main(Main.java:178) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.4-loader.0.15.10-launcher.1.0.1.jar:1.0.1]
апр 22 14:47:30 gate minecraft[689295]: [14:47:30] [main/ERROR]: Parsing error loading recipe wormhole:advanced_target_cell
апр 22 14:47:30 gate minecraft[689295]: com.google.gson.JsonParseException: Not a JSON object: null
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_156.method_47526(class_156.java:1005) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_1863.method_17720(class_1863.java:131) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
апр 22 14:47:30 gate minecraft[689295]:         at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_156.method_43498(class_156.java:944) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_156.method_43499(class_156.java:932) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.server.Main.main(Main.java:178) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.4-loader.0.15.10-launcher.1.0.1.jar:1.0.1]
апр 22 14:47:30 gate minecraft[689295]: [14:47:30] [main/ERROR]: Parsing error loading recipe wormhole:advanced_target_device
апр 22 14:47:30 gate minecraft[689295]: com.google.gson.JsonParseException: Not a JSON object: null
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_156.method_47526(class_156.java:1005) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_1863.method_17720(class_1863.java:131) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
апр 22 14:47:30 gate minecraft[689295]:         at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_156.method_43498(class_156.java:944) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.class_156.method_43499(class_156.java:932) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.minecraft.server.Main.main(Main.java:178) ~[server-intermediary.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.10.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.10.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.10.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.10.jar:?]
апр 22 14:47:30 gate minecraft[689295]:         at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.4-loader.0.15.10-launcher.1.0.1.jar:1.0.1]
```

**Steps to Reproduce**
No spetial steps. Just install mod in fabric and run.
Other stuff from mod - usable.

**Comment by SuperMartijn642** [comment]
I have fixed it now in version 1.1.15a for Fabric and Forge on Minecraft 1.20.3 and 1.20.4.
Thank you for reporting the issue!
